# Generated by Django 2.0 on 2018-05-17 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='assist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='belong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='college',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('intro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('credit', models.DecimalField(decimal_places=1, max_digits=3)),
                ('capacity', models.IntegerField()),
                ('intro', models.TextField()),
                ('type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='discipline',
            fields=[
                ('discipline_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('intro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='evaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.DecimalField(decimal_places=2, max_digits=3)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='learn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.course')),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studnet_id', models.IntegerField()),
                ('discipline_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.college')),
            ],
        ),
        migrations.CreateModel(
            name='minor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studnet_id', models.IntegerField()),
                ('discipline_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='operation',
            fields=[
                ('operation_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='pre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmp_course_id', models.IntegerField()),
                ('pre_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.course')),
            ],
        ),
        migrations.CreateModel(
            name='quit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.course')),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('dorm', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='suspend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.student')),
            ],
        ),
        migrations.CreateModel(
            name='takeup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.course')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.room')),
            ],
        ),
        migrations.CreateModel(
            name='teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.course')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.college')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='attrib',
            fields=[
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.account')),
                ('nickname', models.CharField(max_length=40)),
                ('picture', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('exp', models.IntegerField()),
                ('coin', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='teach',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.teacher'),
        ),
        migrations.AddField(
            model_name='takeup',
            name='time_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.time'),
        ),
        migrations.AddField(
            model_name='quit',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.student'),
        ),
        migrations.AlterUniqueTogether(
            name='minor',
            unique_together={('studnet_id', 'discipline_id')},
        ),
        migrations.AddField(
            model_name='master',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='major',
            unique_together={('studnet_id', 'discipline_id')},
        ),
        migrations.AddField(
            model_name='log',
            name='operation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.operation'),
        ),
        migrations.AddField(
            model_name='learn',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.student'),
        ),
        migrations.AddField(
            model_name='evaluate',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.student'),
        ),
        migrations.AddField(
            model_name='evaluate',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.teacher'),
        ),
        migrations.AddField(
            model_name='belong',
            name='college_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.college'),
        ),
        migrations.AddField(
            model_name='belong',
            name='major_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.major'),
        ),
        migrations.AddField(
            model_name='assist',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.course'),
        ),
        migrations.AddField(
            model_name='assist',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.student'),
        ),
        migrations.AddField(
            model_name='apply',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.course'),
        ),
        migrations.AddField(
            model_name='apply',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.student'),
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('teacher_id', 'college_id')},
        ),
        migrations.AlterUniqueTogether(
            name='teach',
            unique_together={('teacher_id', 'course_id')},
        ),
        migrations.AlterUniqueTogether(
            name='takeup',
            unique_together={('course_id', 'time_id', 'room_id')},
        ),
        migrations.AlterUniqueTogether(
            name='suspend',
            unique_together={('student_id', 'course_id')},
        ),
        migrations.AlterUniqueTogether(
            name='quit',
            unique_together={('student_id', 'course_id')},
        ),
        migrations.AlterUniqueTogether(
            name='pre',
            unique_together={('tmp_course_id', 'pre_course_id')},
        ),
        migrations.AlterUniqueTogether(
            name='master',
            unique_together={('teacher_id', 'college_id')},
        ),
        migrations.AlterUniqueTogether(
            name='learn',
            unique_together={('student_id', 'course_id')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluate',
            unique_together={('student_id', 'teacher_id')},
        ),
        migrations.AlterUniqueTogether(
            name='belong',
            unique_together={('major_id', 'college_id')},
        ),
        migrations.AlterUniqueTogether(
            name='assist',
            unique_together={('student_id', 'course_id')},
        ),
        migrations.AlterUniqueTogether(
            name='apply',
            unique_together={('student_id', 'course_id')},
        ),
    ]
