# Generated by Django 2.0.6 on 2018-06-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learn',
            name='grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learn',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attrib',
            name='coin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attrib',
            name='exp',
            field=models.IntegerField(null=True),
        ),
    ]
