# Generated by Django 2.0.6 on 2018-06-08 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180608_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.student')),
                ('takeup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.takeup')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('student_id', 'takeup_id', 'position')},
        ),
    ]
