# Generated by Django 2.0.6 on 2018-06-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180608_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='time',
            name='start',
            field=models.TimeField(),
        ),
    ]
