# Generated by Django 2.0.6 on 2018-06-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180608_1710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='exam',
            new_name='examination',
        ),
    ]
