# Generated by Django 2.0.6 on 2018-06-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180609_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
